### ISSUE TITLE
Custom BouncyCastle.Security.SecureRandom not available on WP8.1

### ISSUE THREAD

**Issue by fonix232** [NicolasDorier/NBitcoin#53]
As the title says. At the moment it is the only class that implements IRandom and can be used with it - and it is not available on Windows Phone.

**Comment by Thashiznets** [comment]
Reading your book, I see you are suggesting pretty much what I have done, datetime.not + currentthreadID  + system runtime combined with KDF, however I also thought of another neat way to get entropy, read the contents of a section of memory! What do you think?

**Comment by fonix232** [comment]
@Thashiznets while it could be done. mobile platforms would represent a good part of the use of NBitcoin - and neither WinPhones nor Xamarin allows direct memory access.

For better entropy, why not read pseudorandom-defined data from a file? E.g. get a few pseudorandom numbers, based on that, get a path to a file, and get a pseudorandom number for start position to read (e.g. a 2MB file, get a number from ranges 1 - [2MB - 8kB], and read the data from there.

**Comment by Thashiznets** [comment]
@fonix232 I think you can initialize a defined size array and then because it resides in memory allocated to the mobile app you then access the array and you get the random contents of what was in the memory isn't that right? Because arrays are by reference so you are always dealing with memory spots behind the scenes.

As for the files, remember in the mobile environments you are restricted to a sandbox, and possibly the media library so it may be feasible to sha256 a music file filename or something like that!

**Comment by fonix232** [comment]
Actually WP8.1 allows direct file access in specific places, but yes, browsing into the music library is just as feasible - if it exists. For example, all my music is on Spotify, which uses its own storage.

**Comment by Thashiznets** [comment]
@fonix232 yea like documents, downloads, music etc, but as you say it depends on user having content in those areas not really a guarantee. There should always be junk data in memory, I actually found ways to get junk memory data when calling some native/unmanaged code when I was doing Unicode NFKD normalisation stuff so it is definitely doable in WP.

**Comment by Thashiznets** [comment]
@fonix232 @NicolasDorier oh also I use byte[] guidBytes = Guid.NewGuid().ToByteArray(); I get a GUID and use it as well :)

**Comment by NicolasDorier** [comment]
As fonix said, reading random value in memory is problematic, since there is no crossplateform way to do it. If there is no crossplateform way, then the solution is to used plateform specific PRNG (eg: SecureRandom of Java, RNGCryptoProvider for windows desktop)

Adding entropy manually would protect against the underlying PRNG bugs and backdoor though.
As I talk in the book, I added a RandomUtils.AddEntropy method.

The same remark hold for reading a pseudo random file. (not portable)

The Guid.NewGuid() is interesting but the security depends on the underlying implementation of it. And I doubt it use plateform specific PRNG, which mean that the entropy only have clock time, so a very bad one.

**Comment by Thashiznets** [comment]
Hi @NicolasDorier like you I was skeptical about the entropy of GUID and how it remained random and so I traced the function back to the underlying Win32 functions and I found that it uses the ethernet or token ring MAC address. I imagine it starts as a hash of that and then keeps hashing for each subsequent GUID. It looks good as a source of entropy to me, of course just like you mention in your book, if attacker has access to machine they can get runtime, same would apply fir GUID but I believe it certainly helps bump up the bits of entropy. I am currently writing a method to return a hash of random memory bytes, I found I can exploit the unmanaged NormalizeString function to return bigger byte array than it should which sees it grabbing whatever is in memory so I get nice random byte array after hashing :)

**Comment by NicolasDorier** [comment]
Very interesting, so if the attacker knows your MAC (which is not private info on internal network), it basically has access to your key. In some case, it might be worse than timestamp.

However, yes, it bump up entropy. It protects a bit if there is an underlying bug in the PRNG.
Are you doing the NormalizeString hack for protecting yourself against the RNGCryptoServiceProvider of windows ? Because it already hash a number of internal state like.

Surely enough, adding your own entropy protect against malware messing up the prng.


    The current process ID (GetCurrentProcessID).
    The current thread ID (GetCurrentThreadID).
    The tick count since boot time (GetTickCount).
    The current time (GetLocalTime).
    Various high-precision performance counters (QueryPerformanceCounter).
    An MD4 hash of the user's environment block, which includes username, computer name, and search path. [...]
    High-precision internal CPU counters, such as RDTSC, RDMSR, RDPMC


[Source](http://en.wikipedia.org/wiki/CryptGenRandom)

**Comment by Thashiznets** [comment]
Yea MAC and possibly they use a timestamp as well to ensure uniqueness? Unsure but yes as with anything constant they can get it if machine compromised. RNGCryptoServiceProvider is unfortunately not common between WinRT and WinPhoneRT at the moment, they are putting crypto stuff into .NET Core at the moment they inform me, but in the mean time I am using BouncyCastles Secure random with my own entropy.

**Comment by NicolasDorier** [comment]
What about [CryptographicBuffer](http://stackoverflow.com/questions/14582008/what-cryptographically-secure-options-are-there-for-creating-random-numbers-in-w) ?

**Comment by Thashiznets** [comment]
Problem is CryptographicBuffer is part of Windows.Security.Cryptography and Windows.Security is WinRT only and not available for me in a PCL Targeting Windows 8.1 (WinRT) and Windows Phone 8.1 (WindowsPhoneRT).

**Comment by NicolasDorier** [comment]
I think you should use the CryptographicBuffer for WinRT and the RngCryptoServiceProvider for Windows Phone.
The way you can do that is by having an "Initialize" method in each plateform specific project that affect RandomUtils.Random with the plateform specific implementation.

**Comment by Thashiznets** [comment]
I don't agree. I think your random should not chop and change between platforms. Given that it is easy to have Hashing algorithm on all platforms, it is very simple to create a common RNG on all platforms and I feel that SHA(your own entropy) is simple, efficient and safe, can be shared across all platforms and you don't have the problem where one RNG may be found insecure on one platform yet fine on another etc. Also you control the RNG and can account for it, as opposed to trusting the platform which is what happened to the Android Wallet if I'm not mistaken.

**Comment by NicolasDorier** [comment]
Well, you can protect against plateform RNG with your own entropy. (and yes, android one was flawed)
Using your own, also mean that if there is a bug in it, then it is still present everywhere.

What I would fear by using a custom RNG is to not have a sufficient entropy, when plateform PRNG give us some assurance about it.

If you want to use your own, then I would advice that at least you use some custom random input from your user. (like moving the mouse randomly)

**Comment by Thashiznets** [comment]
But what if the entropy adding mechanism is flawed in the platform specific RNG? What if instead of adding seed material it clobbers it instead? So you think you are adding all this entropy but may in fact not be? You see what I mean? And yes I am handling all the entropy and seed generation in my custom random implementation so there is no way a user can go wrong. I have datetime, currentthreadid, systemruntime, guid, threadraceconditionentropy, processoraffinity all rolled into one AND kdf for certainty. This is cross platform and can be used in any WinRT/WinPhoneRT and can easily be ported to Android/iOS

**Comment by Thashiznets** [comment]
Oh also remember, .NET crypto stuff still lives in the land of Sha1, so Rfc2898DeriveBytes (The .NET PBKDF2) is still using Sha1, but we have been advised now to use Sha256 and stronger so you may find these platform RNGs a bit lacking!

**Comment by NicolasDorier** [comment]
I see, yes it is a valid concern, like I said, android prng was flawed not so long time ago, so that's not paranoid.
I must say that I would not be confident enough about knowing if the entropy you are using is secure.
That's why I like using plateform PRNG which delegate that to the microsoft/apple/google... but well even such can be broken and hacked, so I might be wrong to prefer them instead of your own + KDF.

**Comment by Thashiznets** [comment]
But my entropy creation is in my open source code so you can see for yourself the entropy creation. You can even look at the SecureRandom class in the BouncyCastle source to check that the entropy is being correctly used, this is what I did and I have absolute confidence in my solution which is using Sha256 and finally sha512 in the kdf. Honestly, Sha2 is the best thing since sliced bread!

**Comment by NicolasDorier** [comment]
It is not the algorithm that I necessarily don't trust.
It is more whether if the entropy is breakable by bruteforcing. But I guess with the KDF it should be fine.

**Comment by Thashiznets** [comment]
Indeed, I'm confident that I don't need to use KDF, but I do for good measure.

**Comment by Thashiznets** [comment]
@NicolasDorier hey mate I forgot to mention to you however feel free to put my BIP39 implementation into NBitcoin if you wish. It would be super easy to use your IRandom instead of what I'm doing if you prefer for the cross platform!

**Comment by NicolasDorier** [comment]
Thanks ! I was going to ask you if I can do that at one point. In fact I had several demands for BIP39.
I'll do it.

**Comment by NicolasDorier** [comment]
@Thashiznets I included BIP39. Your implementation helped a lot, but I did lots of refactoring. (I kept your credit on the Mnemonic class)

However the string normalization is not supported in all plateform, so I did not included it in my portable libraries :(
However, it is support on Android.

I've seen your solution to get a portable Normalize, but I suspect it works only on Windows. (so don't work on other plateforms)
I should ship a Windows-only portable lib at one point.

**Comment by Thashiznets** [comment]
@NicolasDorier nice work! Indeed you are correct, the Normalisation is the reason I removed WP Silverlight support as it is a pinvoked Win32 call and can only be done in the Full .NET or .NET Core project types, the old WP Silverlight don't allow pinvoke so that is why I have ditched the legacy Silverlight and focussing on .NET Core now as it is the future.

Correct, my Normalise solution is reliant on Win32 API so yep you are correct that it is only windows.

I saw you were getting the lists real time, the reason I don't like dynamicly changing wordlists is that if you use the indeces and it points to a changed word, you get totally different derived bytes! I mean the wordlist I wouldn't think should change, but being open source it is a danger!

**Comment by NicolasDorier** [comment]
I opened another #60 issue.
It is impossible that they change that, since it would break existing shipped trezor.
Sometimes the list is updated but I think it does not break old mnemonic.

However, I think I will hardcode the lists in the lib like you did... Because I can't port the GithubWordlistSource (rely on HttpClient, which is not in my profiles)

For the normalized form, you just had to do use String.Normalize(NormalizationForm.FormKD) if you only support WIN32.

I intend to generate a substitution table of characters to their normalized forms and just hardcode it in the portable lib. Since it is potentially big, I'll only do it for well used characters, and just throw an exception for others.

**Comment by Thashiznets** [comment]
Believe it or not, String.Normalize is another of those not available in .NET Core methods, only full .NET at the moment which is why I need to pinvoke the Win32 NormalizeString

**Comment by NicolasDorier** [comment]
Funny thing that Android support it :D

**Comment by NicolasDorier** [comment]
@Thashiznets I finished by hard coding the dictionaries, as well as a good deal of KD normalization.
Now BIP39 is portable ! :)

**Comment by Thashiznets** [comment]
@NicolasDorier Nice! Have you tested your KD mapping against the official test vectors just for safety? Particularly it would be good to do with the Jap tests as the Jap tests catch people out when not normalising properly.

**Comment by NicolasDorier** [comment]
Yes I did. You can open NBitcoin.Portable.sln, and run the NBitcoin.Portable.Tests.
I test both, the portable versions and the full windows version.

**Comment by Thashiznets** [comment]
Ok that's excellent work!

**Comment by NicolasDorier** [comment]
I'm closing that, I will add new Guid at initialization as entropy data only, and provide specific implementation of IRandom for specific plateform when I'll be able to compile on them.
