### ISSUE TITLE
Portable library missing parts

### ISSUE THREAD

**Issue by fonix232** [NicolasDorier/NBitcoin#56]
I've decided to collect all missing parts and to-dos into one big issue so that it can be solved step-by-step.

* - [ ] NBitcoin namespace
  * - [x] Account
    * Needs removal of Spending, Unspent, etc. Portable exclusions
  * TODO
* - [ ] Payment namespace
  * - [x] BitcoinUriBuilder, UriHelper, HttpUtility, HttpEncoder ( #54 )
  * - [ ] PaymentRequest, PaymentACK, Proto
      * Needs protobuf-net with Profile111 instead of Profile136
* - [ ] Protocol namespace
  * - [x] Payload, BitcoinSerializablePayload, UnknownPayload, TxPayload, PayloadAttribute ( #55 )
  * - [x] InventoryVector ( #55 ) 
  * - [x] NetworkAddress
    * Needs IPEndPoint (not available in WinRT?)
  * - [ ] UPnPLease
    * Needs IPEndPoint, NodeServer
  * - [x] NodeServer, NodeListener, Node
    * Needs Socket
  * - [x] Peer, PeerTable, PeerTableRepository
    * Needs NetworkAddress, IPEndPoint
  * - [ ] ProtocolTrace
    * System.Diagnostics.Trace is now less exposed than public
  * Payloads
    * - [x] AddrPayload 
      * Needs Sockets
    * - [x] AlertPayload, BlockPayload, GetAddrPayload, GetBlocksPayload, GetDataPayload, GetHeadersPayload, HeadersPayload, InvPayload, MempoolPayload, PingPayload, PongPayload, VerAckPayload  ( #55 )
    * - [x] VersionPayload
      * Needs Sockets
* [x] RPC namespace 
* [x] Scanning namespace (TODO)

**Comment by fonix232** [comment]
So Nicolas, do you think that that implementation could be used?

Although it is not exactly a portable non-language-specific library, I think it could be ported with relative ease.

**Comment by NicolasDorier** [comment]
What, the berkeley socket implementation from the winrt version ?
I'm not convinced about the "ported with relative ease".

And even if it is, I'm not sure we can even play an app would be able to play nicely with tombstoning events from microsoft. I think it is easier to just keep the devices dumb, and use a web service that do the heavy lifting.
Also, we should not forget that NBitcoin allows you to speak with the network, but is not a full node implementation. It does not validate anything, it just handle the communication part of the protocol.

I am working on such service. The code will not be open source though. (Using NBitcoin.Indexer under the hood)
Take a look at http://rapidbase-test.azurewebsites.net/

**Comment by Thashiznets** [comment]
100% agree with you Nicholas. As you say, tombstoning and the short time frame and intervals for background tasks makes running a full node on WinRT/WinPhoneRT impossible. As Nicholas says, they best thing would be to have a full node in the cloud and devices can register addresses and receive notifications from the cloud node whilst keeping private keys on device. Like Nicholas I am going to have a go at achieving this.

**Comment by NicolasDorier** [comment]
Thashiznets, you might be interested by my other project "NBitcoin.Indexer".
It use azure table as a backend. I'm building on top of it.

The user API is not stable these days since I accomodate a lot (using it in 3 different customer project).
However, the indexing works well and is stable.
This is what I am using for http://rapidbase-test.azurewebsites.net/

**Comment by Thashiznets** [comment]
@NicolasDorier yea nice one! I'll have a look, I want to write my own code because that way I can easily maintain it when protocol changes etc, I'm not very good at deciphering other peoples code haha! But definitely that kind of thing you are doing is the future. Big cloud node clusters serving devices is the way it needs to be, I believe full node P2P rates are dropping off due to the implementation od SPV clients using bloom filtering etc.

**Comment by NicolasDorier** [comment]
Ok, if you want to do it, for making a fast and scalable storage here is what I've done. (works very well)
When I index a transaction, I don't put in the same line the previous txout. It makes indexing quick.

However, on query time, I fetch the previous txout and store it in the same line, so that later on a request will take 1 database call. (Lazy Loading)

When I index balance movement (wallet or address), I store it so the natural order is Height descending. Data being : height, txid, blockid, coinspent,coinreceived.
Same thing, I don't store the spent coin in the line. I do it at query time lazily.

**Comment by NicolasDorier** [comment]
I don't intend to implement BIP70 in portable library. As I have stated in the bitcoin dev mailing list, asking to a mobile/tablet developer to implement a cross plateform and secure certification chain verification is not reasonable.
I recommend to forward the PaymentRequest to a trusted web service that will do the verification on the behalf of the device.

Search for "[Bitcoin-development] BIP70: why Google Protocol Buffers for encoding?" in the mailing list to see my points.

**Comment by Thashiznets** [comment]
@nicolasdorier where can I find the mailing list? Isn't BIP70 a method of creating a payment request for use in QR? Is your concern a man in the middle that might send a malicious payment request in place of the legit one? (valid concern)

**Comment by NicolasDorier** [comment]
You can see [here](http://sourceforge.net/p/bitcoin/mailman/bitcoin-development/?style=threaded/).

My point is by using BIP70, you put the burden of certificate verification on the shoulder of the developer. 

So the developer has 3 choices :
* Hack something himself by shipping some certificate trust store of mozilla, google or whatever, and use a generic X509 framework to validate the chain (what bitcoinj does). But then what happens when a certificate is revocated and trust store should be updated ? Well the response of Mike is that no one care right now, but one could implement it... which is also very hard.
* Or the developer can use a generic X509 certificate representation and use the trust store of its plateform to validate the chain... but in this case you need to provide type mapping between the generic one and each of your target plateform. Such code is hard to develop right, and hard to test.
* Or the developer can ask to a trusted third party web service to do the chain validation and parsing for him.

Also protobuf is not supported perfectly on all plateforms, unlike JSON.

My point is that payment requests should be simple JSON document over HTTPS, so the plateform take care of the validation and not the developer. Garzik and Mike point was that with BIP70, devices like Trezor don't need a full SSL layer... True but mobile users have one, so BIP70 is not well adapted for them.

**Comment by NicolasDorier** [comment]
I am closing this PR, I implemented all I could.

UPNP is removed from NBitcoin, I don't plan to make BIP70 portable for now, for the reason I enumerated.
